[package]
name = "microrust-start"
version = "0.1.0"
authors = ["huntc <huntchr@gmail.com>"]
edition = "2018"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.6"
embedded-hal = "0.2"
panic-halt = "0.2"
